import pulumi
import pulumi_aws as aws
import pulumi_gcp as gcp
import yaml

# --- 1. CONFIGURATION & MAPPINGS ---
VM_SIZES = {
    "small": {"aws": "t3.micro", "gcp": "e2-micro"},
    "medium": {"aws": "t3.medium", "gcp": "e2-medium"},
}

# Simple startup script to verify the VM is live
vm_startup_script = """#!/bin/bash
echo "Hello from Simpleform VM!" > index.html
nohup python3 -m http.server 80 &
"""

REGION_MAP = {
    "us-east": {"aws": "us-east-1", "gcp": "us-east1"},
    "us-west": {"aws": "us-west-2", "gcp": "us-west1"},
    "europe": {"aws": "eu-central-1", "gcp": "europe-west3"},
}

# Load the user configuration from the YAML generated by cli.py
with open("simpleform.yaml", "r") as f:
    config = yaml.safe_load(f)

settings = config.get("settings", {})
target_region = REGION_MAP.get(settings.get("region", "us-east"))
is_public = settings.get("public_access", False)
use_versioning = settings.get("versioning", False)

# --- 2. DYNAMIC AWS AMI SEARCH ---
# This finds the latest Ubuntu 22.04 image automatically for the current region
ubuntu_ami = aws.ec2.get_ami(
    most_recent=True,
    filters=[
        {
            "name": "name",
            "values": ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"],
        },
        {"name": "virtualization-type", "values": ["hvm"]},
    ],
    owners=["099720109477"],  # Official Canonical ID
)

# --- 3. RESOURCE LOGIC ---

# OPTION A: STORAGE BUCKETS
if config["resource"] == "bucket":
    if config["cloud"] == "aws":
        bucket = aws.s3.Bucket(
            config["name"],
            versioning=aws.s3.BucketVersioningArgs(enabled=use_versioning),
        )

        ownership = aws.s3.BucketOwnershipControls(
            f"{config['name']}-ownership",
            bucket=bucket.id,
            rule={"object_ownership": "BucketOwnerPreferred"},
        )

        pab = aws.s3.BucketPublicAccessBlock(
            f"{config['name']}-pab",
            bucket=bucket.id,
            block_public_acls=False,
            block_public_policy=False,
            ignore_public_acls=False,
            restrict_public_buckets=False,
        )

        if is_public:
            aws.s3.BucketAclV2(
                f"{config['name']}-acl",
                bucket=bucket.id,
                acl="public-read",
                opts=pulumi.ResourceOptions(depends_on=[ownership, pab]),
            )

        pulumi.export(
            "bucket_url", bucket.id.apply(lambda id: f"https://{id}.s3.amazonaws.com")
        )
        pulumi.export("cloud_provider", "Amazon Web Services")

    elif config["cloud"] == "gcp":
        bucket = gcp.storage.Bucket(
            config["name"],
            location=target_region["gcp"],
            versioning=gcp.storage.BucketVersioningArgs(enabled=use_versioning),
        )

        if is_public:
            gcp.storage.BucketIAMMember(
                f"{config['name']}-public-access",
                bucket=bucket.name,
                role="roles/storage.objectViewer",
                member="allUsers",
            )

        pulumi.export("bucket_url", bucket.self_link)
        pulumi.export("cloud_provider", "Google Cloud Platform")

# OPTION B: VIRTUAL MACHINES
elif config["resource"] == "server":
    if config["cloud"] == "aws":
        # Create Security Group for Web Traffic
        group = aws.ec2.SecurityGroup(
            f"{config['name']}-sg",
            description="Allow HTTP traffic",
            ingress=[
                {
                    "protocol": "tcp",
                    "from_port": 80,
                    "to_port": 80,
                    "cidr_blocks": ["0.0.0.0/0"],
                }
            ],
        )

        # Launch EC2 Instance using the Dynamic AMI found above
        server = aws.ec2.Instance(
            config["name"],
            instance_type=VM_SIZES[settings.get("size", "small")]["aws"],
            ami=ubuntu_ami.id,
            vpc_security_group_ids=[group.id],
            user_data=vm_startup_script,
        )
        pulumi.export("server_public_ip", server.public_ip)
        pulumi.export("cloud_provider", "Amazon Web Services")

    elif config["cloud"] == "gcp":
        # Create Firewall Rule
        firewall = gcp.compute.Firewall(
            f"{config['name']}-fw",
            allows=[{"protocol": "tcp", "ports": ["80"]}],
            source_ranges=["0.0.0.0/0"],
        )

        # Launch Compute Engine Instance
        server = gcp.compute.Instance(
            config["name"],
            machine_type=VM_SIZES[settings.get("size", "small")]["gcp"],
            boot_disk={"initializeParams": {"image": "debian-cloud/debian-11"}},
            network_interfaces=[{"network": "default", "accessConfigs": [{}]}],
            metadata_startup_script=vm_startup_script,
        )

        pulumi.export(
            "server_public_ip",
            server.network_interfaces[0]["accessConfigs"][0]["natIp"],
        )
        pulumi.export("cloud_provider", "Google Cloud Platform")
